# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 07:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Song',
        ),
    ]
